schema_version: 1

context:
  name: pronto
  version: "2.7.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pronto-${{ version }}.tar.gz
  sha256: ba3a07d4d84f71deb56ff4dea987ea513c21ad9c3ce172375647ff2471982b36

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=61.0
    - pip
  run:
    - python >=${{ python_min }}
    - chardet >=5.0,<6.dev0
    - fastobo >=0.13.0,<0.15
    - networkx >=2.3,<4.0
    - python-dateutil >=2.8,<3.dev0

tests:
  - python:
      imports:
        - pronto
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Python frontend to ontologies.
  license: MIT
  license_file: COPYING
  homepage: https://github.com/althonos/pronto

extra:
  recipe-maintainers:
    - hadim
